---
- name: Update APT cache and upgrade system
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600

- name: Install basic utility packages
  apt:
    name:
      - bc
      - iptables
      - python3
      - git
      - curl
      - ffmpeg
    state: present