FROM --platform=linux/arm64 python:3.10-slim-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    git build-essential cmake \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

RUN pip install --upgrade pip setuptools wheel pybind11 meson ninja

RUN git clone https://github.com/atw1020/sente.git sente-src

WORKDIR /build/sente-src
# Fix version python setup.py
RUN sed -i 's/">=3.8.*"/">=3.8"/' setup.py
# Fix headers C++ manquants (Algorithm)
RUN sed -i '1s;^;#include <algorithm>\n;' src/Utils/Tree.h
RUN sed -i '1s;^;#include <algorithm>\n;' src/Utils/SGF/SGFNode.cpp

RUN python3 setup.py bdist_wheel

CMD cp dist/*.whl /output/
