---
- name: Téléchargement du script d'installation officiel Docker
  get_url:
    url: https://get.docker.com
    dest: /tmp/install-docker.sh
    mode: '0755'

- name: Exécution du script d'installation
  command: /tmp/install-docker.sh
  args:
    creates: /usr/bin/docker

- name: Ajout de l'utilisateur courant au groupe docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Installation des dépendances Python pour Ansible Docker
  apt:
    name: python3-docker
    state: present

- name: Copier l'archive Docker sur la Raspberry Pi
  copy:
    src: ../app/tenukigo-app.tar.gz 
    dest: "/home/{{ ansible_user }}/tenukigo-app.tar.gz"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  register: docker_archive_copy

- name: Charger l'image Docker depuis l'archive locale
  docker_image:
    name: localhost/tenukigo-app
    tag: latest
    source: load
    load_path: "/home/{{ ansible_user }}/tenukigo-app.tar.gz"
    timeout: 600
  when: docker_archive_copy.changed

- name: Lancer le conteneur TenukiGo
  docker_container:
    name: tenukigo-app
    image: localhost/tenukigo-app:latest
    pull: missing
    state: started
    restart_policy: always
    privileged: true
    recreate: "{{ docker_archive_copy.changed }}"
    volumes:
      - "/home/{{ ansible_user }}/go_videos:/app/go_videos"
      - "/home/{{ ansible_user }}/output_sgf:/app/output_sgf"