---
- name: Download official Docker installation script
  get_url:
    url: https://get.docker.com
    dest: /tmp/install-docker.sh
    mode: '0755'

- name: Execute installation script
  command: /tmp/install-docker.sh
  args:
    creates: /usr/bin/docker

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Install Python dependencies for Ansible Docker
  apt:
    name: python3-docker
    state: present

- name: Copy Docker archive to Raspberry Pi
  copy:
    src: ../app/tenukigo-app.tar.gz 
    dest: "/home/{{ ansible_user }}/tenukigo-app.tar.gz"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  register: docker_archive_copy

- name: Load Docker image from local archive
  docker_image:
    name: localhost/tenukigo-app
    tag: latest
    source: load
    load_path: "/home/{{ ansible_user }}/tenukigo-app.tar.gz"
    timeout: 600
  when: docker_archive_copy.changed

- name: Start TenukiGo container
  docker_container:
    name: tenukigo-app
    image: localhost/tenukigo-app:latest
    pull: missing
    state: started
    restart_policy: always
    privileged: true
    recreate: "{{ docker_archive_copy.changed }}"
    volumes:
      - "{{ videos_dir }}:/app/go_videos"
      - "{{ sgf_dir }}:/app/output_sgf"