---
- name: Téléchargement du script d'installation officiel Docker
  get_url:
    url: https://get.docker.com
    dest: /tmp/install-docker.sh
    mode: '0755'

- name: Exécution du script d'installation
  command: /tmp/install-docker.sh
  args:
    creates: /usr/bin/docker

- name: Ajout de l'utilisateur 'pi' au groupe docker
  user:
    name: pi
    groups: docker
    append: yes
  # Permet de lancer docker sans 'sudo'