[gocamera]
#! Remplacer par l'IP de la raspberry
172.20.10.2 ansible_user=mao

# Pour utiliser une clef SSH :
# ansible_ssh_private_key_file=~/.ssh/id_rsa

# Pour utiliser ssh_pass :
# ansible_ssh_pass=password
