---
- name: Restart hostapd
  service:
    name: hostapd
    state: restarted

- name: Restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: Restart NetworkManager
  service:
    name: NetworkManager
    state: restarted
